"""Emit the 3 share-card harnesses, one per language.

The card is a page rather than a PNG somebody once exported, for the reason
og-harness.html's own comment gives: the old card could not be regenerated,
only recreated, and it drifted a whole rebrand behind the site. This script is
the same defence one level up. The English harness carried its service line as
typed text, so the day chrome.py renamed a service the card would have kept
selling the old one, in the one image every share shows.

DERIVED, NOT TYPED. The service line is that language's chrome FOOT_LABELS[0]
joined with middots: the same 5 words the footer of every page already uses,
read from the same module, so the card and the site cannot call a service two
different things. Nothing else on the card is a sentence, which is why this
file needs no key in chrome.py and no entry in any stamp table.

THREE STATIC FILES, not one harness with a query parameter. The harness loads
the site's own /css/tokens.css over http.server, and a ?lang= switch would
need a script in the page to rewrite the line, which is a moving part in a
file whose entire job is to hold still for a camera.

TO REGENERATE THE HARNESSES:  python assets/og/build_harness.py
TO REGENERATE THE 3 PNGs:
  python -m http.server 8099            # from the project root
  then screenshot, at exactly 1200x630 and deviceScaleFactor 1:
    /assets/og/og-harness.html     -> og-image.png
    /assets/og/og-harness-it.html  -> og-image-it.png
    /assets/og/og-harness-sq.html  -> og-image-sq.png
  Any headless browser will do. There is deliberately no node dependency here.
"""
import io
import os
import sys

ROOT = os.path.dirname(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
sys.path.insert(0, os.path.join(ROOT, ".build"))
import chrome  # noqa: E402
import chrome_it  # noqa: E402
import chrome_sq  # noqa: E402

NL = chr(10)
HERE = os.path.dirname(os.path.abspath(__file__))

# (html lang, harness file, the chrome module the service line is read from).
# The filenames pair with og-image.png / og-image-it.png / og-image-sq.png,
# which is the same suffix rule i18n.PREFIX applies to a page.
CARDS = [
    ("en", "og-harness.html", chrome),
    ("it", "og-harness-it.html", chrome_it),
    ("sq", "og-harness-sq.html", chrome_sq),
]

TEMPLATE = """<!doctype html>
<html lang="{lang}">
<head>
<meta charset="UTF-8">
<title>og harness ({lang})</title>
<!--
  GENERATED by build_harness.py. Edit that script, never this file: the
  service line below is chrome{mod_suffix}.FOOT_LABELS[0] and a hand edit here
  is exactly the drift the generator exists to end.

  The share card, as a page rather than as a PNG somebody once exported.
  It uses the site's own tokens and its own self-hosted faces, so it cannot
  drift from the site again without somebody noticing.

  TO REGENERATE: see build_harness.py's docstring, in this directory.
-->
<link rel="stylesheet" href="/css/tokens.css">
<link rel="stylesheet" href="/css/fonts.css">
<style>
  html, body {{ margin: 0; padding: 0; background: var(--paper); }}
  .card {{ position: relative; width: 1200px; height: 630px; overflow: hidden;
    background: var(--paper); display: flex; flex-direction: column;
    justify-content: center; padding: 0 84px; box-sizing: border-box; }}

  /* the same ten results the hero climbs, at the same 6% ink */
  .serp {{ position: absolute; left: 84px; right: 84px; top: 128px; height: 300px; }}
  .serp i {{ position: absolute; left: 0; right: 46px; height: 1px;
    background: rgba(19, 22, 28, 0.06); }}
  .serp i::after {{ content: attr(data-n); position: absolute; right: -34px;
    top: -8px; width: 28px; text-align: right; font-family: var(--font-body);
    font-variant-numeric: tabular-nums; font-size: 13px; letter-spacing: 0.06em;
    color: rgba(90, 96, 112, 0.5); }}

  /* the lockup is inline-block so "studio" can right-align to the wordmark's
     own edge rather than to the card, which is what puts it in the wedge the
     climb opens under the risen k */
  .lock {{ position: relative; z-index: 1; display: inline-block; }}
  .wm {{ font-family: var(--font-display); font-weight: 500; font-size: 200px;
    line-height: 1; letter-spacing: -0.03em; color: var(--ink);
    white-space: nowrap; }}
  .wm span {{ display: inline-block; }}
  .wm .k {{ color: var(--red); margin-left: -0.012em; }}

  .studio {{ display: block; text-align: right; margin-top: -0.06em;
    font-family: var(--font-body); font-weight: 500; font-size: 34px;
    letter-spacing: 0.34em; text-indent: 0.34em; color: var(--slate);
    line-height: 1; }}

  .rule {{ position: absolute; left: 84px; right: 84px; bottom: 112px;
    height: 1px; background: var(--rule); }}
  /* 19px, not the 21px the English-only card wore: the Albanian line is the
     longest of the 3 and one size has to hold all of them, or the cards stop
     being one design photographed 3 times */
  .svcs {{ position: absolute; left: 84px; bottom: 64px;
    font-family: var(--font-body); font-weight: 600; font-size: 19px;
    letter-spacing: 0.05em; color: var(--ink); white-space: nowrap; }}
  .svcs b {{ font-weight: 600; color: var(--slate); padding: 0 9px; }}
</style>
</head>
<body>
  <div class="card">
    <div class="serp">
      <i style="top:0"   data-n="1"></i><i style="top:33px"  data-n="2"></i>
      <i style="top:66px" data-n="3"></i><i style="top:99px"  data-n="4"></i>
      <i style="top:132px" data-n="5"></i><i style="top:165px" data-n="6"></i>
      <i style="top:198px" data-n="7"></i><i style="top:231px" data-n="8"></i>
      <i style="top:264px" data-n="9"></i><i style="top:297px" data-n="10"></i>
    </div>

    <div class="lock">
      <div class="wm">
        <span style="transform:translateY(0em)">m</span><span style="transform:translateY(-0.028em)">i</span><span style="transform:translateY(-0.056em)">n</span><span style="transform:translateY(-0.084em)">a</span><span style="transform:translateY(-0.112em)">r</span><span style="transform:translateY(-0.14em)">a</span><span style="transform:translateY(-0.168em)">n</span><span class="k" style="transform:translateY(-0.196em)">k</span>
      </div>
      <div class="studio">studio</div>
    </div>

    <div class="rule"></div>
    <div class="svcs">{services}</div>
  </div>
</body>
</html>
"""


def write_if_changed(path, body):
    old = io.open(path, encoding="utf-8").read() if os.path.exists(path) else None
    if old == body:
        return "unchanged"
    io.open(path, "w", encoding="utf-8", newline=NL).write(body)
    return "written"


for lang, fn, mod in CARDS:
    line = "<b>&middot;</b>".join(mod.FOOT_LABELS[0])
    body = TEMPLATE.format(lang=lang, services=line,
                           mod_suffix="" if lang == "en" else "_" + lang)
    print(fn, write_if_changed(os.path.join(HERE, fn), body))
