"""Read the daily series back out of the Search Console screenshot.

Run by hand, not by the build:  python .build/trace_proof.py
It writes `.build/proof_data.py`, which IS imported by the build.

Why this exists. The homepage prints 4 figures for watch.al and then shows a
screenshot of the chart they came from. The chart is Google's, in Google's blue
and purple, and it is the loudest thing on a site that is otherwise ink, red and
paper. Drawing our own line needs the daily numbers, and the daily numbers were
never exported: the repo has the 4 totals in clients.py and nothing else.

They are recoverable. The screenshot is a line chart with labelled axes, so the
pixels ARE the data at the resolution the chart was drawn. This reads them back.

What makes it honest rather than a drawing. Two totals are published
independently of this file, 741 clicks and 71.1k impressions, and neither was
used to produce the trace. Summing the traced days and comparing is therefore a
real test, and it is one a hand-drawn approximation would fail:

    clicks         743 vs    741   +0.3%
    impressions  71108 vs  71100   +0.0%

Two separate totals reconciling to one pixel calibration is the evidence that
the calibration is right and the shape is the real one. The remaining ~2% is
line width and anti-aliasing, so the build normalises each series onto its
published total. Shape from the pixels, totals from Search Console.

What this does NOT support: any per-day figure. One pixel is about 0.1 clicks
and 6 impressions, the lines are 2px wide and cross each other, so a single
day carries roughly +/-0.5 clicks. Draw the shape, print the totals, never
quote a day.
"""

import io
import os

from PIL import Image                                    # not a build dependency

HERE = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.dirname(HERE)
SRC = os.path.join(ROOT, "assets", "proof", "source", "3month.png")

# Calibration, all of it measured off the image rather than guessed. Re-measured
# on 2026-08-23 for the second screenshot; every constant here moved.
# Horizontal gridlines sit at y = 354, 437 and 521, which is 83.5px per 8 clicks
# and per 500 impressions, putting zero at 604.5. The clicks line bottoms out at
# y = 604, which is the confirmation: the trace found the axis on its own.
Y_ZERO, Y_PER = 604.5, 83.5
CLICKS_PER_BAND, IMPR_PER_BAND = 8.0, 500.0
X_FIRST, X_LAST, DAYS = 534, 1787, 92        # 25 May to 24 August 2026 inclusive
BLUE, PURPLE = (66, 133, 244), (94, 53, 177)
Y_TOP, Y_BOT = 340, 620

# The 2 figures Search Console publishes for this window, and the window
# itself. Typed once. They sat in 5 places until 2026-08-23, which is 5 places
# to miss when a new screenshot arrives, and a printout, a guard and a
# generated docstring quietly disagreeing is the kind of wrong nobody sees.
CLICKS, IMPRESSIONS = 741, 71100
WINDOW = "25 May to 24 August 2026"


def _near(c, t, tol=40):
    return abs(c[0] - t[0]) + abs(c[1] - t[1]) + abs(c[2] - t[2]) <= tol


def _series(px, target, scale):
    """One day per column, the mean y of that column's coloured pixels.

    None where the other line covers this one. The caller interpolates: a gap
    is 1 day out of 90 between 2 known neighbours, and dropping it instead
    would quietly cost the total the day's traffic.
    """
    out = []
    for d in range(DAYS):
        x = X_FIRST + (X_LAST - X_FIRST) * d / (DAYS - 1)
        hits = [y for xx in (int(x) - 1, int(x), int(x) + 1)
                for y in range(Y_TOP, Y_BOT) if _near(px[xx, y], target)]
        out.append(None if not hits
                   else max(0.0, (Y_ZERO - sum(hits) / len(hits)) / Y_PER * scale))
    return out


def _fill(v):
    v = list(v)
    for i, x in enumerate(v):
        if x is None:
            lo = next((v[j] for j in range(i - 1, -1, -1) if v[j] is not None), None)
            hi = next((v[j] for j in range(i + 1, len(v)) if v[j] is not None), None)
            v[i] = (lo + hi) / 2 if lo is not None and hi is not None else (lo or hi or 0.0)
    return v


def main():
    im = Image.open(SRC).convert("RGB")
    px = im.load()
    clicks = _fill(_series(px, BLUE, CLICKS_PER_BAND))
    impr = _fill(_series(px, PURPLE, IMPR_PER_BAND))
    sc, si = sum(clicks), sum(impr)
    print("traced %d days" % DAYS)
    print("  clicks      %7.0f vs %6d  %+.1f%%"
          % (sc, CLICKS, 100 * (sc - CLICKS) / CLICKS))
    print("  impressions %7.0f vs %6d  %+.1f%%"
          % (si, IMPRESSIONS, 100 * (si - IMPRESSIONS) / IMPRESSIONS))
    if (abs(sc - CLICKS) / CLICKS > 0.06
            or abs(si - IMPRESSIONS) / IMPRESSIONS > 0.06):
        raise SystemExit("trace does not reconcile with the published totals; "
                         "the calibration is wrong and nothing is written")

    body = io.StringIO()
    w = body.write
    w('"""The watch.al daily series, traced from the Search Console screenshot.\n\n')
    w("GENERATED by .build/trace_proof.py from assets/proof/source/3month.png.\n")
    w("Do not hand-edit: rerun the tracer, which re-checks the totals before it\n")
    w("writes. That docstring carries the method and its limits.\n\n")
    w("%d days, %s, as (clicks, impressions) per day. These\n" % (DAYS, WINDOW))
    w("are the RAW traced values. They sum to %.0f and %.0f against published\n" % (sc, si))
    w("totals of %d and %d, so the build scales each series onto its total\n"
      % (CLICKS, IMPRESSIONS))
    w("before drawing. Shape from the pixels, totals from Search Console.\n\n")
    w("Never quote a single day from this. One pixel is about 0.1 clicks and 6\n")
    w("impressions and the two lines cross, so a day carries roughly +/-0.5.\n")
    w('"""\n\n')
    w("TOTAL_CLICKS = %d\n" % CLICKS)
    w("TOTAL_IMPRESSIONS = %d\n\n" % IMPRESSIONS)
    w("# (clicks, impressions), one tuple per day\n")
    w("DAILY = [\n")
    for c, i in zip(clicks, impr):
        w("    (%.2f, %.1f),\n" % (c, i))
    w("]\n")
    out = os.path.join(HERE, "proof_data.py")
    io.open(out, "w", encoding="utf-8", newline="\n").write(body.getvalue())
    print("wrote .build/proof_data.py")


if __name__ == "__main__":
    main()
